# Generated by Django 3.1.1 on 2022-10-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoretable',
            old_name='residential_noise',
            new_name='residential_Noise',
        ),
    ]
