# Generated by Django 3.1.1 on 2022-10-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScoreTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zipcode", models.IntegerField()),
                ("residential_noise", models.FloatField(max_length=10)),
            ],
        ),
    ]
