# Generated by Django 3.2.16 on 2022-11-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_scoretable_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoretable",
            name="grade",
            field=models.CharField(default="N", max_length=10),
        ),
    ]
