# Generated by Django 3.2.16 on 2022-10-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221025_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
