# Generated by Django 3.2.16 on 2022-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_add_user_grades"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoretable",
            name="userGrace",
        ),
        migrations.AddField(
            model_name="scoretable",
            name="userGrade",
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name="scoretable",
            name="gradeCount",
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name="scoretable",
            name="userAvg",
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
