# Generated by Django 3.2.16 on 2022-11-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("app", "0006_auto_20221031_1427"),
    ]

    operations = [
        migrations.CreateModel(
            name="forum",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="anonymous", max_length=200)),
                ("email", models.CharField(max_length=200, null=True)),
                ("topic", models.CharField(max_length=300)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discuss", models.CharField(max_length=1000)),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.forum",
                    ),
                ),
            ],
        ),
    ]
