# Generated by Django 3.2.16 on 2022-11-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_discussion_forum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="forum",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
