# Generated by Django 3.2.16 on 2022-11-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20221101_0138"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="forum",
            new_name="ForumPost",
        ),
        migrations.RenameField(
            model_name="discussion",
            old_name="forum",
            new_name="forumPost",
        ),
    ]
