# Generated by Django 3.2.16 on 2022-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_forumpost_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="anonymous", max_length=200),
        ),
    ]
