# Generated by Django 3.2.16 on 2022-11-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rename_discuss_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoretable",
            name="borough",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="forumPost",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.forumpost",
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="zipcode",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.scoretable",
            ),
        ),
    ]
