# Generated by Django 3.2.16 on 2022-11-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_auto_20221109_1918"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoretable",
            name="constructionImpact",
            field=models.FloatField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
