# Generated by Django 3.2.16 on 2022-11-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_scoretable_constructionimpact"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoretable",
            name="treeCensus",
            field=models.FloatField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
