# Generated by Django 3.2.16 on 2022-11-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_scoretable_treecensus"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoretable",
            name="parkCount",
            field=models.FloatField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
