# Generated by Django 3.2.16 on 2022-11-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scoretable_grade'),
        ('app', '0019_scoretable_grade'),
    ]

    operations = [
    ]
